---
# tasks file for roles/nginx_setup

- name: Install NGINX
  apt:
    name: nginx
    state: present
  become: yes

- name: Ensure the necessary directories are present
  file:
    path: "/usr/share/nginx/html"
    state: directory
  become: yes

- name: Configure NGINX to serve a static webpage
  template:
    src: index.html.j2
    dest: "/usr/share/nginx/html/index.html"
  become: yes

- name: Start NGINX
  service:
    name: nginx
    state: started
  become: yes
